import {loadArticleTitle} from "@/datocms/queries"
import {addComment, loadComments} from "@/firebase/admin"
import {siteUrl} from "@/shared/constants"
import {getAuth} from "firebase-admin/auth"
import nodemailer from "nodemailer"
import {CommentsApp} from "./CommentsApp"

export function Comments({slug}: {slug: string}) {
  async function saveComment(formData: FormData) {
    "use server"
    const text = formData.get("comment")?.toString().trim() ?? ""
    const userId = formData.get("userId")?.toString().trim() ?? ""
    if (!text || !userId) {
      throw Error(`400: Invalid payload ${{comment: text, userId}}`)
    }
    const [{article}, user]: [
      Awaited<ReturnType<typeof loadArticleTitle>>,
      Awaited<ReturnType<ReturnType<typeof getAuth>["getUser"]>>,
    ] = await Promise.all([loadArticleTitle(slug), getAuth().getUser(userId)])
    if (!article) {
      throw Error(`404: no article found for slug "${slug}"`)
    }
    if (!user) {
      throw Error(`404: no user found for id "${userId}"`)
    }
    const {displayName, email, photoURL, uid} = user
    await addComment(slug, {text, user: {displayName, email, photoURL, uid}})
    transporter.sendMail({
      from: process.env.NODEMAILER_EMAIL,
      html: `
        <p>${text}</p>
        <p>${siteUrl}/posts/${slug}</p>
        <p>${email}</p>
        <p>🚨🚨 This is an autogenerated email from an unmonitored mailbox, please do not reply 🚨🚨</p>
      `,
      subject: `${displayName} commented on ${article.title}`,
      to:
        process.env.NODE_ENV === "production"
          ? "monismargaret@gmail.com"
          : "mmonis77@gmail.com",
    })
    return loadComments(slug)
  }
  return <CommentsApp {...{saveComment, slug}} />
}

const transporter = nodemailer.createTransport({
  auth: {
    pass: process.env.NODEMAILER_PASSWORD,
    user: process.env.NODEMAILER_EMAIL,
  },
  service: "gmail",
})
